export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

export const CHANGE_SIGNIN_EMAIL = "CHANGE_SIGNIN_EMAIL";
export const CHANGE_SIGNIN_PASSWORD = "CHANGE_SIGNIN_PASSWORD";

export const CHANGE_SIGNUP_NAME = "CHANGE_SIGNUP_NAME";
export const CHANGE_SIGNUP_EMAIL = "CHANGE_SIGNUP_EMAIL";
export const CHANGE_SIGNUP_PASSWORD = "CHANGE_SIGNUP_PASSWORD";
export const CHANGE_SIGNUP_ERROR = "CHANGE_SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SWITCH_SIGN_FORM = "SWITCH_SIGN_FORM";
export const CHANGE_SIGNIN_ERROR = "CHANGE_SIGNIN_ERROR";

export const CHANGE_RESET_PASSWORD_EMAIL = "CHANGE_RESET_PASSWORD_EMAIL";
export const CHANGE_RESET_PASSWORD_ERROR = "CHANGE_RESET_PASSWORD_ERROR";