export const START_SELECTING_TASK = "START_SELECTING_TASK";
export const UPDATE_SELECTING_TASK = "UPDATE_SELECTING_TASK";
export const STOP_SELECTING_TASK = "STOP_SELECTING_TASK";

export const START_CREATING_TASK = "START_CREATING_TASK";
export const STOP_CREATING_TASK = "STOP_CREATING_TASK";
export const CHANGE_NEWTASK_CATEGORY = "CHANGE_NEWTASK_CATEGORY";
export const CHANGE_NEWTASK_NAME = "CHANGE_NEWTASK_NAME";
export const CHANGE_NEWTASK_DESCRIPTION = "CHANGE_NEWTASK_DESCRIPTION";
export const CHANGE_NEWTASK_ICON = "CHANGE_NEWTASK_ICON";
export const CHANGE_NEWTASK_COLOR = "CHANGE_NEWTASK_COLOR";

export const SEND_NEWTASK_TO_SERVER = "SEND_NEWTASK_TO_SERVER";

export const LOAD_TASKS_SUCCESS = "LOAD_TASKS_SUCCESS";
export const LOAD_TASKS_LOADING = "LOAD_TASKS_LOADING";
export const LOAD_TASKS_FAILURE = "LOAD_TASKS_FAILURE";

export const START_DELETING_TASK = "START_DELETING_TASK";
export const STOP_DELETING_TASK = "STOP_DELETING_TASK";